plugins {
    id 'com.android.application'
}

android {
    namespace 'com.brainshift.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.brainshift.app'
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName "2.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
